package com.ws.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.ws.service.WSService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-09-04T16:06:03.663+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "WSServiceImpService", 
                  wsdlLocation = "http://localhost:6344/ws?wsdl",
                  targetNamespace = "http://impl.service.ws.com/") 
public class WSServiceImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.ws.com/", "WSServiceImpService");
    public final static QName WSServiceImpPort = new QName("http://impl.service.ws.com/", "WSServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:6344/ws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSServiceImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:6344/ws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSServiceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSServiceImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSServiceImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSService
     */
    @WebEndpoint(name = "WSServiceImpPort")
    public WSService getWSServiceImpPort() {
        return super.getPort(WSServiceImpPort, WSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSService
     */
    @WebEndpoint(name = "WSServiceImpPort")
    public WSService getWSServiceImpPort(WebServiceFeature... features) {
        return super.getPort(WSServiceImpPort, WSService.class, features);
    }

}
