package com.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-09-04T16:06:03.596+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.ws.com/", name = "WSService")
@XmlSeeAlso({ObjectFactory.class})
public interface WSService {

    @WebMethod
    @RequestWrapper(localName = "getWeatcher", targetNamespace = "http://service.ws.com/", className = "com.ws.service.GetWeatcher")
    @ResponseWrapper(localName = "getWeatcherResponse", targetNamespace = "http://service.ws.com/", className = "com.ws.service.GetWeatcherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getWeatcher(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
